# Generated by Django 2.2.12 on 2020-05-06 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_description', models.CharField(max_length=100)),
                ('gateway_MAC', models.IntegerField(unique=True)),
                ('gateway_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_description', models.CharField(max_length=100)),
                ('node_MAC', models.IntegerField(unique=True)),
                ('node_x', models.IntegerField()),
                ('node_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(max_length=15)),
                ('users_surname', models.CharField(max_length=25)),
                ('users_login', models.CharField(max_length=10)),
                ('users_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Node_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_data_getdata', models.TextField()),
                ('node_data_time', models.DateField()),
                ('node_data_battery', models.IntegerField()),
                ('node_data_node_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ms.Node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ms.Type'),
        ),
    ]
