# Generated by Django 2.2.12 on 2020-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RenameField(
            model_name='node_data',
            old_name='node_data_node_id',
            new_name='node_data_node',
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gateway_image',
            field=models.ImageField(null=True, upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='node_data',
            name='node_data_time',
            field=models.DateTimeField(),
        ),
    ]
