# Generated by Django 2.2.12 on 2020-05-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0002_auto_20200506_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_data',
            name='node_data_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms.Node'),
        ),
    ]
