# Generated by Django 2.2.12 on 2020-05-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0004_auto_20200506_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='gateway_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='Node_Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_gateway_id_gateway', models.ManyToManyField(to='ms.Gateway')),
                ('node_gateway_id_node', models.ManyToManyField(to='ms.Node')),
            ],
        ),
    ]
