# Generated by Django 2.2.12 on 2020-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0005_auto_20200511_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='gateway_node',
            field=models.ManyToManyField(to='ms.Node'),
        ),
        migrations.DeleteModel(
            name='Node_Gateway',
        ),
    ]
